apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server-deployment
spec:
  selector:
    matchLabels:
      app: redispod
  template:
    metadata:
      labels:
        app: redispod
    spec:
      containers:
        - name: redis-container
          image: redis:latest
